// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ExternalPolygonsGeoJSON = {
    msid: number;
    nameofarea: string;
    positionindicator: string;
    geom: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PolygonCreate = {
    title: string;
    buffer_size?: number;
    coordinates: string;
    positionindicator: string;
};

export type PolygonPublic = {
    title: string;
    buffer_size?: number;
    id: string;
    owner_id: string;
    positionindicator: string;
    original_geometry?: ({
    [key: string]: unknown;
} | null);
    buffered_geometry?: ({
    [key: string]: unknown;
} | null);
};

export type PolygonsPublic = {
    data: Array<PolygonPublic>;
    count: number;
};

export type PolygonUpdate = {
    title?: (string | null);
    buffer_size?: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AipPolygonsReadExternalPolygonsData = {
    limit?: number;
    skip?: number;
};

export type AipPolygonsReadExternalPolygonsResponse = (Array<ExternalPolygonsGeoJSON>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PolygonsReadPolygonsData = {
    limit?: number;
    skip?: number;
};

export type PolygonsReadPolygonsResponse = (PolygonsPublic);

export type PolygonsCreatePolygonData = {
    requestBody: PolygonCreate;
};

export type PolygonsCreatePolygonResponse = (PolygonPublic);

export type PolygonsReadPolygonData = {
    id: string;
};

export type PolygonsReadPolygonResponse = (PolygonPublic);

export type PolygonsUpdatePolygonData = {
    id: string;
    requestBody: PolygonUpdate;
};

export type PolygonsUpdatePolygonResponse = (PolygonPublic);

export type PolygonsDeletePolygonData = {
    id: string;
};

export type PolygonsDeletePolygonResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);