"""update db

Revision ID: 91ea3157c3b5
Revises: bd391d16ba69
Create Date: 2025-10-13 17:03:43.159231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91ea3157c3b5'
down_revision: Union[str, Sequence[str], None] = 'bd391d16ba69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aip_data',
    sa.Column('msid', sa.Integer(), nullable=False),
    sa.Column('nameofarea', sa.String(), nullable=False),
    sa.Column('positionindicator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typeofarea', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('msid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aip_data')
    # ### end Alembic commands ###
