"""update models

Revision ID: b3c2ff8afb49
Revises: f6d4f880c7ef
Create Date: 2026-02-16 22:11:37.064273

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b3c2ff8afb49'
down_revision = 'f6d4f880c7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
