"""Init table

Revision ID: ce96025c8a79
Revises: 9a58dbf9916e
Create Date: 2026-02-21 23:24:46.334917

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce96025c8a79'
down_revision = '9a58dbf9916e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
