"""update polygonbase

Revision ID: e08de3bdb9b7
Revises: 91ea3157c3b5
Create Date: 2025-10-25 23:27:35.500295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e08de3bdb9b7'
down_revision: Union[str, Sequence[str], None] = '91ea3157c3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polygon', sa.Column('positionindicator', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True))
    op.add_column('polygon', sa.Column('original_geometry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('polygon', sa.Column('buffered_geometry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polygon', 'buffered_geometry')
    op.drop_column('polygon', 'original_geometry')
    op.drop_column('polygon', 'positionindicator')
    # ### end Alembic commands ###
