name: Update Tag

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Get Commits
        id: get_commit_messages
        run: |
          # If no tag, use all commits
          if [ -z "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            commits=$(git log --pretty=format:"* %s" HEAD)
          else
            commits=$(git log --pretty=format:"* %s" ${{ steps.get_latest_tag.outputs.latest_tag }}..HEAD)
          fi
          echo "Commits:"
          echo "$commits"
          commits_escaped=$(echo "$commits" | awk '{printf "%s\\n", $0}')
          echo "messages=$commits_escaped" >> $GITHUB_OUTPUT

      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ steps.semver.outputs.next || 'v0.0.1' }}
          github_token: ${{ github.token }}
          tag_prefix: ''
          tag_message: |
            Changes since last release:
            ${{ steps.get_commit_messages.outputs.messages }}
